C
C*DK MASJ3R2
      SUBROUTINE EIRENE_MASJ3R2 (A,I,J,K,B,C)
      USE EIRMOD_PRECISION
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
      CHARACTER(40), INTENT(IN) :: A
      REAL(DP), INTENT(IN) :: B, C
      INTEGER, INTENT(IN) :: I,J,K
      WRITE (iunout,60) A,I,J,K,B,C
   60 FORMAT (1X,A40/,3X,3(I6,3X),2(1PE12.4,3X))
      RETURN
      END SUBROUTINE EIRENE_MASJ3R2
