#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec 22 10:11:02 2019

@author: nathanbartlett
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 11 11:08:38 2019

@author: nathanbartlett
"""


#---------------------------------------------------------------------------------------------------------------------------------------------




def run(FILE_in,FILE_out,PLS_TEMP_DATA_FILE = 'NONE',PLS_DENS_DATA_FILE = 'NONE',ATM_DENS_DATA_FILE = 'NONE',MOL_DENS_DATA_FILE = 'NONE',ION_DENS_DATA_FILE = 'NONE',DIRECTORY = ''):



    '''
    This function takes the input and output of an EIRENE Standalone run and creates a Dataset with the dimensions of SPECIES and ITERATION
        and the RAW DATA of DENSITY and TEMPERATURE.
    '''
    import xarray as xr
    import eirenex.intern as IC
    #----------------------------------

    #Set up variables
    NUM_PRINTOUT_CONDITIONAL_LIST = ''
    VOL_AVG_DATA_TYPES = []
    SUR_AVG_DATA_TYPES = []
    ITERATION = 0
    TIME_STP = 0
    DATASET_DICT = {}
    FWD_MAIN_COND = 0
    FWD_MAIN_IND  = 0



    #Import and read I/O files
    FILE_IN_LINES, FILE_OUT_LINES,FILE_NAME,PLS_TEMP_FT_DATA_LINES,PLS_DENS_FT_DATA_LINES,ATM_DENS_FT_DATA_LINES,MOL_DENS_FT_DATA_LINES,ION_DENS_FT_DATA_LINES = IC.upload_files(FILE_in,FILE_out,PLS_TEMP_DATA_FILE,PLS_DENS_DATA_FILE,ATM_DENS_DATA_FILE,MOL_DENS_DATA_FILE,ION_DENS_DATA_FILE)

    ##Get Block 11 Data
    for i in range(len(FILE_IN_LINES)):

        if ('*** 11' in FILE_IN_LINES[i]):

            NUM_PRINTOUT_CONDITIONAL_LIST, VOL_AVG_NUM,SUR_AVG_NUM,VOL_AVG_DICT,SUR_AVG_DICT = IC.block_11_data(FILE_IN_LINES,i, VOL_AVG_DATA_TYPES, SUR_AVG_DATA_TYPES)

    #First readthrough of output file
    while (FWD_MAIN_COND == 0):

        if (' IUNIN =' in FILE_OUT_LINES[FWD_MAIN_IND]):

            META_DESCRIPTION_LINE = IC.get_MDL(FILE_OUT_LINES,FWD_MAIN_IND)

        if ('N1ST        =' in FILE_OUT_LINES[FWD_MAIN_IND]):

            XR_NUM = IC.get_XR_NUM(FILE_OUT_LINES,FWD_MAIN_IND)

        if ('N2ND        =' in FILE_OUT_LINES[FWD_MAIN_IND]):

            YP_NUM = IC.get_YP_NUM(FILE_OUT_LINES,FWD_MAIN_IND)

        if ('N3RD        =' in FILE_OUT_LINES[FWD_MAIN_IND]):

            ZT_NUM = IC.get_ZT_NUM(FILE_OUT_LINES,FWD_MAIN_IND)

        if ('NATM        =' in FILE_OUT_LINES[FWD_MAIN_IND]):

            ATM_NUM = IC.get_ATM_NUM(FILE_OUT_LINES,FWD_MAIN_IND)

        if ('NMOL        =' in FILE_OUT_LINES[FWD_MAIN_IND]):

            MOL_NUM = IC.get_MOL_NUM(FILE_OUT_LINES,FWD_MAIN_IND)

        if ('NION        =' in FILE_OUT_LINES[FWD_MAIN_IND]):

            ION_NUM = IC.get_ION_NUM(FILE_OUT_LINES,FWD_MAIN_IND)

        if ('NPLS        =' in FILE_OUT_LINES[FWD_MAIN_IND]):

            PLS_NUM = IC.get_PLS_NUM(FILE_OUT_LINES,FWD_MAIN_IND)

        if (' DATE:' in FILE_OUT_LINES[FWD_MAIN_IND]):

            DATE = IC.get_DATE(FILE_OUT_LINES,FWD_MAIN_IND)

        if (' TIME:' in FILE_OUT_LINES[FWD_MAIN_IND]):

            TIME = IC.get_TIME(FILE_OUT_LINES,FWD_MAIN_IND)

        if ('ITERATIONS:            1  TO' in FILE_OUT_LINES[FWD_MAIN_IND]):

            ITERATION_NUM = IC.get_IN(FILE_OUT_LINES,FWD_MAIN_IND)

        if ('TIME CYCLES:            1  TO' in FILE_OUT_LINES[FWD_MAIN_IND]):

            TIME_STP_NUM = IC.get_TSN(FILE_OUT_LINES,FWD_MAIN_IND)

        if FWD_MAIN_IND >= (len(FILE_OUT_LINES) - 1):
            FWD_MAIN_COND = 1

        FWD_MAIN_IND += 1   #Keep indexing through this first loop we created

#|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
#Dealing with output file now

    #Plasma Species Arrays Temp
    PSPC_INDX_TEMP,PLASMA_SPC_NAMES_TEMP,VPTA,PTA1DXR_INDX_TEMP,PTA1DXR,PTA1DYP_INDX_TEMP,PTA1DYP,PTA1DZT_INDX_TEMP,PTA1DZT,PT2YP_ZT_INDEX_TEMP,PT2YP_ZT,PT2XR_YP_INDEX_TEMP,PT2XR_YP,PT2XR_ZT_INDEX_TEMP,PT2XR_ZT,PT3DXR_INDEX1_TEMP,PT3DXR = IC.BUILD_ARRAYS(TIME_STP_NUM,ITERATION_NUM,PLS_NUM,XR_NUM,YP_NUM,ZT_NUM)

    #Plasma Species Arrays Density
    PSPC_INDX_DENS,PLASMA_SPC_NAMES_DENS,VPDA,PDA1DXR_INDX_DENS,PDA1DXR,PDA1DYP_INDX_DENS,PDA1DYP,PDA1DZT_INDX_DENS,PDA1DZT,PD2YP_ZT_INDEX_DENS,PD2YP_ZT,PD2XR_YP_INDEX_DENS,PD2XR_YP,PD2XR_ZT_INDEX_DENS,PD2XR_ZT,PD3DXR_INDEX1_DENS,PD3DXR = IC.BUILD_ARRAYS(TIME_STP_NUM,ITERATION_NUM,PLS_NUM,XR_NUM,YP_NUM,ZT_NUM)

    #Atom density arrays
    ATOM_INDX_DENS,ATOM_SPC_NAMES_DENS,VADA,ADA1DXR_INDX_DENS,ADA1DXR,ADA1DYP_INDX_DENS,ADA1DYP,ADA1DZT_INDX_DENS,ADA1DZT,AD2YP_ZT_INDEX_DENS,AD2YP_ZT,AD2XR_YP_INDEX_DENS,AD2XR_YP,AD2XR_ZT_INDEX_DENS,AD2XR_ZT,AD3DXR_INDEX1_DENS,AD3DXR = IC.BUILD_ARRAYS(TIME_STP_NUM,ITERATION_NUM,ATM_NUM,XR_NUM,YP_NUM,ZT_NUM)

    #Molecule Density Arrays
    MOL_INDX_DENS,MOL_SPC_NAMES_DENS,VMDA,MDA1DXR_INDX_DENS,MDA1DXR,MDA1DYP_INDX_DENS,MDA1DYP,MDA1DZT_INDX_DENS,MDA1DZT,MD2YP_ZT_INDEX_DENS,MD2YP_ZT,MD2XR_YP_INDEX_DENS,MD2XR_YP,MD2XR_ZT_INDEX_DENS,MD2XR_ZT,MD3DXR_INDEX1_DENS,MD3DXR = IC.BUILD_ARRAYS(TIME_STP_NUM,ITERATION_NUM,MOL_NUM,XR_NUM,YP_NUM,ZT_NUM)

    #Test ion density arrays
    ION_INDX_DENS,ION_SPC_NAMES_DENS,VIDA,IDA1DXR_INDX_DENS,IDA1DXR,IDA1DYP_INDX_DENS,IDA1DYP,IDA1DZT_INDX_DENS,IDA1DZT,ID2YP_ZT_INDEX_DENS,ID2YP_ZT,ID2XR_YP_INDEX_DENS,ID2XR_YP,ID2XR_ZT_INDEX_DENS,ID2XR_ZT,ID3DXR_INDEX1_DENS,ID3DXR = IC.BUILD_ARRAYS(TIME_STP_NUM,ITERATION_NUM,ION_NUM,XR_NUM,YP_NUM,ZT_NUM)

    for i in range(len(FILE_OUT_LINES)):

        if ('TALLY:   PLASMA TEMPERATURE' in FILE_OUT_LINES[i]):

            #Get Names
            PLASMA_SPC_NAMES_TEMP = IC.get_NAMES(PLASMA_SPC_NAMES_TEMP,FILE_OUT_LINES,i,ITERATION,TIME_STP,VOL_AVG_DICT[-2])

            #Check for IDENTICALLY ZERO
            PTA1DXR,PTA1DYP,PTA1DZT,FWD_COND,PTA1DXR_INDX_TEMP,PTA1DYP_INDX_TEMP,PTA1DZT_INDX_TEMP,TIME_STP,ITERATION,FWD_IND,PSPC_INDX_TEMP,PT2YP_ZT_INDEX_TEMP,PT2XR_YP_INDEX_TEMP,PT2XR_ZT_INDEX_TEMP,PT3DXR_INDEX1_TEMP = IC.IZ(PTA1DXR,PTA1DYP,PTA1DZT,PTA1DXR_INDX_TEMP,PTA1DYP_INDX_TEMP,PTA1DZT_INDX_TEMP,TIME_STP,ITERATION,i,FILE_OUT_LINES,PSPC_INDX_TEMP,PT2YP_ZT_INDEX_TEMP,PT2XR_YP_INDEX_TEMP,PT2XR_ZT_INDEX_TEMP,PT3DXR_INDEX1_TEMP)

            #Get 0D
            PSPC_INDX_TEMP,VPTA = IC.DENS_0D(PSPC_INDX_TEMP,PLS_NUM,FILE_OUT_LINES,VPTA,i,TIME_STP,ITERATION,FWD_COND)


            #Get 1D-XR
            PTA1DXR,PTA1DXR_INDX_TEMP = IC.get_1D(PTA1DXR_INDX_TEMP,PLS_NUM,FILE_OUT_LINES,PTA1DXR,i,TIME_STP,ITERATION,FWD_COND,'X- OR RADIAL PROFILE','Y- OR POL. AND Z- OR TOR. AVERAGE')

            #Get 1D-YP
            PTA1DYP,PTA1DYP_INDX_TEMP = IC.get_1D(PTA1DYP_INDX_TEMP,PLS_NUM,FILE_OUT_LINES,PTA1DYP,i,TIME_STP,ITERATION,FWD_COND,'Y- OR POLOIDAL PROFILE','X- OR RAD. AND Z- OR TOR. AVERAGE')

            #Get 1D-ZT
            PTA1DZT,PTA1DZT_INDX_TEMP = IC.get_1D(PTA1DZT_INDX_TEMP,PLS_NUM,FILE_OUT_LINES,PTA1DZT,i,TIME_STP,ITERATION,FWD_COND,'Z- OR TOROIDAL PROFILE','X- OR RAD. AND Y- OR POL. AVERAGE')


            #2D Temperature Poloidal Profile across Z, Avg XR
            PT2YP_ZT_INDEX_TEMP,PT2YP_ZT = IC.get_2D(FWD_COND,'Y- OR POLOIDAL PROFILE','X- OR RADIAL AVERAGE','Z- OR TOROIDAL SEGMENT NUMBER',PT2YP_ZT,FILE_OUT_LINES,i,PT2YP_ZT_INDEX_TEMP,TIME_STP,ITERATION,ZT_NUM,PLS_NUM,VOL_AVG_DICT[-2])

            #2D Temperature Radial Profile Across YP, Avg ZT
            PT2XR_YP_INDEX_TEMP,PT2XR_YP = IC.get_2D(FWD_COND,'X- OR RADIAL PROFILE','Z- OR TOROIDAL AVERAGE','Y- OR POLOIDAL SEGMENT NUMBER',PT2XR_YP,FILE_OUT_LINES,i,PT2XR_YP_INDEX_TEMP,TIME_STP,ITERATION,YP_NUM,PLS_NUM,VOL_AVG_DICT[-2])

            #2D Temperature Radial Profile Across ZT, Avg YP
            PT2XR_ZT_INDEX_TEMP,PT2XR_ZT = IC.get_2D(FWD_COND,'X- OR RADIAL PROFILE','Y- OR POLOIDAL AVERAGE','Z- OR TOROIDAL SEGMENT NUMBER',PT2XR_ZT,FILE_OUT_LINES,i,PT2XR_ZT_INDEX_TEMP,TIME_STP,ITERATION,ZT_NUM,PLS_NUM,VOL_AVG_DICT[-2])

            #3D Temperature Radial Profile Across YP and ZT
            PT3DXR_INDEX1_TEMP,PT3DXR = IC.get_3D(FWD_COND,'X- OR RADIAL PROFILE','Z- OR TOROIDAL SEGMENT NUMBER','Y- OR POLOIDAL SEGMENT NUMBER',PT3DXR,FILE_OUT_LINES,PT3DXR_INDEX1_TEMP,TIME_STP,ITERATION,XR_NUM,YP_NUM,ZT_NUM,VOL_AVG_DICT[-2],i)

        if ('PLASMA DENSITY' in FILE_OUT_LINES[i]):


            #Get Names
            PLASMA_SPC_NAMES_DENS = IC.get_NAMES(PLASMA_SPC_NAMES_DENS,FILE_OUT_LINES,i,ITERATION,TIME_STP,VOL_AVG_DICT[-4])

            #Check for IDENTICALLY ZERO
            PDA1DXR,PDA1DYP,PDA1DZT,FWD_COND,PDA1DXR_INDX_DENS,PDA1DYP_INDX_DENS,PDA1DZT_INDX_DENS,TIME_STP,ITERATION,FWD_IND,PSPC_INDX_DENS,PD2YP_ZT_INDEX_DENS,PD2XR_YP_INDEX_DENS,PD2XR_ZT_INDEX_DENS,PD3DXR_INDEX1_DENS = IC.IZ(PDA1DXR,PDA1DYP,PDA1DZT,PDA1DXR_INDX_DENS,PDA1DYP_INDX_DENS,PDA1DZT_INDX_DENS,TIME_STP,ITERATION,i,FILE_OUT_LINES,PSPC_INDX_DENS,PD2YP_ZT_INDEX_DENS,PD2XR_YP_INDEX_DENS,PD2XR_ZT_INDEX_DENS,PD3DXR_INDEX1_DENS)


            #Get Block Average Data
            PSPC_INDX_DENS,VPDA = IC.DENS_0D(PSPC_INDX_DENS,PLS_NUM,FILE_OUT_LINES,VPDA,i,TIME_STP,ITERATION,FWD_COND)


            #Get 1D-XR
            PDA1DXR,PDA1DXR_INDX_DENS = IC.get_1D(PDA1DXR_INDX_DENS,PLS_NUM,FILE_OUT_LINES,PDA1DXR,i,TIME_STP,ITERATION,FWD_COND,'X- OR RADIAL PROFILE','Y- OR POL. AND Z- OR TOR. AVERAGE')

            #Get 1D-YP
            PDA1DYP,PDA1DYP_INDX_DENS = IC.get_1D(PDA1DYP_INDX_DENS,PLS_NUM,FILE_OUT_LINES,PDA1DYP,i,TIME_STP,ITERATION,FWD_COND,'Y- OR POLOIDAL PROFILE','X- OR RAD. AND Z- OR TOR. AVERAGE')

            #Get 1D-ZT
            PDA1DZT,PDA1DZT_INDX_DENS = IC.get_1D(PDA1DZT_INDX_DENS,PLS_NUM,FILE_OUT_LINES,PDA1DZT,i,TIME_STP,ITERATION,FWD_COND,'Z- OR TOROIDAL PROFILE','X- OR RAD. AND Y- OR POL. AVERAGE')


            #2D Density Poloidal Profile across Z, Avg XR
            PD2YP_ZT_INDEX_DENS,PD2YP_ZT = IC.get_2D(FWD_COND,'Y- OR POLOIDAL PROFILE','X- OR RADIAL AVERAGE','Z- OR TOROIDAL SEGMENT NUMBER',PD2YP_ZT,FILE_OUT_LINES,i,PD2YP_ZT_INDEX_DENS,TIME_STP,ITERATION,ZT_NUM,PLS_NUM,VOL_AVG_DICT[-4])

            #2D Density Radial Profile Across YP, Avg ZT
            PD2XR_YP_INDEX_DENS,PD2XR_YP = IC.get_2D(FWD_COND,'X- OR RADIAL PROFILE','Z- OR TOROIDAL AVERAGE','Y- OR POLOIDAL SEGMENT NUMBER',PD2XR_YP,FILE_OUT_LINES,i,PD2XR_YP_INDEX_DENS,TIME_STP,ITERATION,YP_NUM,PLS_NUM,VOL_AVG_DICT[-4])

            #2D Density Radial Profile Across ZT, Avg YP
            PD2XR_ZT_INDEX_DENS,PD2XR_ZT = IC.get_2D(FWD_COND,'X- OR RADIAL PROFILE','Y- OR POLOIDAL AVERAGE','Z- OR TOROIDAL SEGMENT NUMBER',PD2XR_ZT,FILE_OUT_LINES,i,PD2XR_ZT_INDEX_DENS,TIME_STP,ITERATION,ZT_NUM,PLS_NUM,VOL_AVG_DICT[-4])

            #3D Temperature Radial Profile Across YP and ZT
            PD3DXR_INDEX1_DENS,PD3DXR = IC.get_3D(FWD_COND,'X- OR RADIAL PROFILE','Z- OR TOROIDAL SEGMENT NUMBER','Y- OR POLOIDAL SEGMENT NUMBER',PD3DXR,FILE_OUT_LINES,PD3DXR_INDEX1_DENS,TIME_STP,ITERATION,XR_NUM,YP_NUM,ZT_NUM,VOL_AVG_DICT[-4],i)



        if ('PARTICLE DENSITY (ATOMS)' in FILE_OUT_LINES[i]):

            #Get Names
            ATOM_SPC_NAMES_DENS = IC.get_NAMES(ATOM_SPC_NAMES_DENS,FILE_OUT_LINES,i,ITERATION,TIME_STP,VOL_AVG_DICT[1])

            #Get IZ
            ADA1DXR,ADA1DYP,ADA1DZT,FWD_COND,ADA1DXR_INDX_DENS,ADA1DYP_INDX_DENS,ADA1DZT_INDX_DENS,TIME_STP,ITERATION,FWD_IND,ATOM_INDX_DENS,AD2YP_ZT_INDEX_DENS,AD2XR_YP_INDEX_DENS,AD2XR_ZT_INDEX_DENS,AD3DXR_INDEX1_DENS = IC.IZ(ADA1DXR,ADA1DYP,ADA1DZT,ADA1DXR_INDX_DENS,ADA1DYP_INDX_DENS,ADA1DZT_INDX_DENS,TIME_STP,ITERATION,i,FILE_OUT_LINES,ATOM_INDX_DENS,AD2YP_ZT_INDEX_DENS,AD2XR_YP_INDEX_DENS,AD2XR_ZT_INDEX_DENS,AD3DXR_INDEX1_DENS)


            #Get 0D
            ATOM_INDX_DENS,VADA = IC.DENS_0D(ATOM_INDX_DENS,ATM_NUM,FILE_OUT_LINES,VADA,i,TIME_STP,ITERATION,FWD_COND)


            #Get 1D-XR
            ADA1DXR,ADA1DXR_INDX_DENS = IC.get_1D(ADA1DXR_INDX_DENS,ATM_NUM,FILE_OUT_LINES,ADA1DXR,i,TIME_STP,ITERATION,FWD_COND,'X- OR RADIAL PROFILE','Y- OR POL. AND Z- OR TOR. AVERAGE')

            #Get 1D-YP
            ADA1DYP,ADA1DYP_INDX_DENS = IC.get_1D(ADA1DYP_INDX_DENS,ATM_NUM,FILE_OUT_LINES,ADA1DYP,i,TIME_STP,ITERATION,FWD_COND,'Y- OR POLOIDAL PROFILE','X- OR RAD. AND Z- OR TOR. AVERAGE')

            #Get 1D-ZT
            ADA1DZT,ADA1DZT_INDX_DENS = IC.get_1D(ADA1DZT_INDX_DENS,ATM_NUM,FILE_OUT_LINES,ADA1DZT,i,TIME_STP,ITERATION,FWD_COND,'Z- OR TOROIDAL PROFILE','X- OR RAD. AND Y- OR POL. AVERAGE')


            #2D Density Poloidal Profile across Z, Avg XR
            AD2YP_ZT_INDEX_DENS,AD2YP_ZT = IC.get_2D(FWD_COND,'Y- OR POLOIDAL PROFILE','X- OR RADIAL AVERAGE','Z- OR TOROIDAL SEGMENT NUMBER',AD2YP_ZT,FILE_OUT_LINES,i,AD2YP_ZT_INDEX_DENS,TIME_STP,ITERATION,ZT_NUM,ATM_NUM,VOL_AVG_DICT[1])

            #2D Density Radial Profile Across YP, Avg ZT
            AD2XR_YP_INDEX_DENS,AD2XR_YP = IC.get_2D(FWD_COND,'X- OR RADIAL PROFILE','Z- OR TOROIDAL AVERAGE','Y- OR POLOIDAL SEGMENT NUMBER',AD2XR_YP,FILE_OUT_LINES,i,AD2XR_YP_INDEX_DENS,TIME_STP,ITERATION,YP_NUM,ATM_NUM,VOL_AVG_DICT[1])

            #2D Density Radial Profile Across ZT, Avg YP
            AD2XR_ZT_INDEX_DENS,AD2XR_ZT = IC.get_2D(FWD_COND,'X- OR RADIAL PROFILE','Y- OR POLOIDAL AVERAGE','Z- OR TOROIDAL SEGMENT NUMBER',AD2XR_ZT,FILE_OUT_LINES,i,AD2XR_ZT_INDEX_DENS,TIME_STP,ITERATION,ZT_NUM,ATM_NUM,VOL_AVG_DICT[1])

            #3D Temperature Radial Profile Across YP and ZT
            AD3DXR_INDEX1_DENS,AD3DXR = IC.get_3D(FWD_COND,'X- OR RADIAL PROFILE','Z- OR TOROIDAL SEGMENT NUMBER','Y- OR POLOIDAL SEGMENT NUMBER',AD3DXR,FILE_OUT_LINES,AD3DXR_INDEX1_DENS,TIME_STP,ITERATION,XR_NUM,YP_NUM,ZT_NUM,VOL_AVG_DICT[1],i)


        if ('PARTICLE DENSITY (MOLECULES)' in FILE_OUT_LINES[i]):

            #Get Names
            MOL_SPC_NAMES_DENS = IC.get_NAMES(MOL_SPC_NAMES_DENS,FILE_OUT_LINES,i,ITERATION,TIME_STP,VOL_AVG_DICT[2])

            #Get IZ
            MDA1DXR,MDA1DYP,MDA1DZT,FWD_COND,MDA1DXR_INDX_DENS,MDA1DYP_INDX_DENS,MDA1DZT_INDX_DENS,TIME_STP,ITERATION,FWD_IND,MOL_INDX_DENS,MD2YP_ZT_INDEX_DENS,MD2XR_YP_INDEX_DENS,MD2XR_ZT_INDEX_DENS,MD3DXR_INDEX1_DENS = IC.IZ(MDA1DXR,MDA1DYP,MDA1DZT,MDA1DXR_INDX_DENS,MDA1DYP_INDX_DENS,MDA1DZT_INDX_DENS,TIME_STP,ITERATION,i,FILE_OUT_LINES,MOL_INDX_DENS,MD2YP_ZT_INDEX_DENS,MD2XR_YP_INDEX_DENS,MD2XR_ZT_INDEX_DENS,MD3DXR_INDEX1_DENS)


            #Get 0D
            MOL_INDX_DENS,VMDA = IC.DENS_0D(MOL_INDX_DENS,MOL_NUM,FILE_OUT_LINES,VMDA,i,TIME_STP,ITERATION,FWD_COND)


            #Get 1D-XR
            MDA1DXR,MDA1DXR_INDX_DENS = IC.get_1D(MDA1DXR_INDX_DENS,MOL_NUM,FILE_OUT_LINES,MDA1DXR,i,TIME_STP,ITERATION,FWD_COND,'X- OR RADIAL PROFILE','Y- OR POL. AND Z- OR TOR. AVERAGE')

            #Get 1D-YP
            MDA1DYP,MDA1DYP_INDX_DENS = IC.get_1D(MDA1DYP_INDX_DENS,MOL_NUM,FILE_OUT_LINES,MDA1DYP,i,TIME_STP,ITERATION,FWD_COND,'Y- OR POLOIDAL PROFILE','X- OR RAD. AND Z- OR TOR. AVERAGE')

            #Get 1D-ZT
            MDA1DZT,MDA1DZT_INDX_DENS = IC.get_1D(MDA1DZT_INDX_DENS,MOL_NUM,FILE_OUT_LINES,MDA1DZT,i,TIME_STP,ITERATION,FWD_COND,'Z- OR TOROIDAL PROFILE','X- OR RAD. AND Y- OR POL. AVERAGE')


            #2D Density Poloidal Profile across Z, Avg XR
            MD2YP_ZT_INDEX_DENS,MD2YP_ZT = IC.get_2D(FWD_COND,'Y- OR POLOIDAL PROFILE','X- OR RADIAL AVERAGE','Z- OR TOROIDAL SEGMENT NUMBER',MD2YP_ZT,FILE_OUT_LINES,i,MD2YP_ZT_INDEX_DENS,TIME_STP,ITERATION,ZT_NUM,MOL_NUM,VOL_AVG_DICT[2])

            #2D Density Radial Profile Across YP, Avg ZT
            MD2XR_YP_INDEX_DENS,MD2XR_YP = IC.get_2D(FWD_COND,'X- OR RADIAL PROFILE','Z- OR TOROIDAL AVERAGE','Y- OR POLOIDAL SEGMENT NUMBER',MD2XR_YP,FILE_OUT_LINES,i,MD2XR_YP_INDEX_DENS,TIME_STP,ITERATION,YP_NUM,MOL_NUM,VOL_AVG_DICT[2])

            #2D Density Radial Profile Across ZT, Avg YP
            MD2XR_ZT_INDEX_DENS,MD2XR_ZT = IC.get_2D(FWD_COND,'X- OR RADIAL PROFILE','Y- OR POLOIDAL AVERAGE','Z- OR TOROIDAL SEGMENT NUMBER',MD2XR_ZT,FILE_OUT_LINES,i,MD2XR_ZT_INDEX_DENS,TIME_STP,ITERATION,ZT_NUM,MOL_NUM,VOL_AVG_DICT[2])


            #3D Temperature Radial Profile Across YP and ZT
            MD3DXR_INDEX1_DENS,MD3DXR = IC.get_3D(FWD_COND,'X- OR RADIAL PROFILE','Z- OR TOROIDAL SEGMENT NUMBER','Y- OR POLOIDAL SEGMENT NUMBER',MD3DXR,FILE_OUT_LINES,MD3DXR_INDEX1_DENS,TIME_STP,ITERATION,XR_NUM,YP_NUM,ZT_NUM,VOL_AVG_DICT[2],i)

        if ('PARTICLE DENSITY (TEST IONS)' in FILE_OUT_LINES[i]):

            #Get Names
            ION_SPC_NAMES_DENS = IC.get_NAMES(ION_SPC_NAMES_DENS,FILE_OUT_LINES,i,ITERATION,TIME_STP,VOL_AVG_DICT[3])

            #Check IZ
            IDA1DXR,IDA1DYP,IDA1DZT,FWD_COND,IDA1DXR_INDX_DENS,IDA1DYP_INDX_DENS,IDA1DZT_INDX_DENS,TIME_STP,ITERATION,FWD_IND,ION_INDX_DENS,ID2YP_ZT_INDEX_DENS,ID2XR_YP_INDEX_DENS,ID2XR_ZT_INDEX_DENS,ID3DXR_INDEX1_DENS = IC.IZ(IDA1DXR,IDA1DYP,IDA1DZT,IDA1DXR_INDX_DENS,IDA1DYP_INDX_DENS,IDA1DZT_INDX_DENS,TIME_STP,ITERATION,i,FILE_OUT_LINES,ION_INDX_DENS,ID2YP_ZT_INDEX_DENS,ID2XR_YP_INDEX_DENS,ID2XR_ZT_INDEX_DENS,ID3DXR_INDEX1_DENS)

            #Get 0D
            ION_INDX_DENS,VIDA = IC.DENS_0D(ION_INDX_DENS,ION_NUM,FILE_OUT_LINES,VIDA,i,TIME_STP,ITERATION,FWD_COND)

            #Get 1D-XR
            IDA1DXR,IDA1DXR_INDX_DENS = IC.get_1D(IDA1DXR_INDX_DENS,ION_NUM,FILE_OUT_LINES,IDA1DXR,i,TIME_STP,ITERATION,FWD_COND,'X- OR RADIAL PROFILE','Y- OR POL. AND Z- OR TOR. AVERAGE')

            #Get 1D-YP
            IDA1DYP,IDA1DYP_INDX_DENS = IC.get_1D(IDA1DYP_INDX_DENS,ION_NUM,FILE_OUT_LINES,IDA1DYP,i,TIME_STP,ITERATION,FWD_COND,'Y- OR POLOIDAL PROFILE','X- OR RAD. AND Z- OR TOR. AVERAGE')

            #Get 1D-ZT
            IDA1DZT,IDA1DZT_INDX_DENS = IC.get_1D(IDA1DZT_INDX_DENS,ION_NUM,FILE_OUT_LINES,IDA1DZT,i,TIME_STP,ITERATION,FWD_COND,'Z- OR TOROIDAL PROFILE','X- OR RAD. AND Y- OR POL. AVERAGE')


            #2D Density Poloidal Profile across Z, Avg XR
            ID2YP_ZT_INDEX_DENS,ID2YP_ZT = IC.get_2D(FWD_COND,'Y- OR POLOIDAL PROFILE','X- OR RADIAL AVERAGE','Z- OR TOROIDAL SEGMENT NUMBER',ID2YP_ZT,FILE_OUT_LINES,i,ID2YP_ZT_INDEX_DENS,TIME_STP,ITERATION,ZT_NUM,ION_NUM,VOL_AVG_DICT[3])

            #2D Density Radial Profile Across YP, Avg ZT
            ID2XR_YP_INDEX_DENS,ID2XR_YP = IC.get_2D(FWD_COND,'X- OR RADIAL PROFILE','Z- OR TOROIDAL AVERAGE','Y- OR POLOIDAL SEGMENT NUMBER',ID2XR_YP,FILE_OUT_LINES,i,ID2XR_YP_INDEX_DENS,TIME_STP,ITERATION,YP_NUM,ION_NUM,VOL_AVG_DICT[3])

            #2D Density Radial Profile Across ZT, Avg YP
            ID2XR_ZT_INDEX_DENS,ID2XR_ZT = IC.get_2D(FWD_COND,'X- OR RADIAL PROFILE','Y- OR POLOIDAL AVERAGE','Z- OR TOROIDAL SEGMENT NUMBER',ID2XR_ZT,FILE_OUT_LINES,i,ID2XR_ZT_INDEX_DENS,TIME_STP,ITERATION,ZT_NUM,ION_NUM,VOL_AVG_DICT[3])


            #3D Temperature Radial Profile Across YP and ZT
            ID3DXR_INDEX1_DENS,ID3DXR = IC.get_3D(FWD_COND,'X- OR RADIAL PROFILE','Z- OR TOROIDAL SEGMENT NUMBER','Y- OR POLOIDAL SEGMENT NUMBER',ID3DXR,FILE_OUT_LINES,ID3DXR_INDEX1_DENS,TIME_STP,ITERATION,XR_NUM,YP_NUM,ZT_NUM,VOL_AVG_DICT[3],i)


        if ('CALLED AFTER ITERATION' in FILE_OUT_LINES[i]):
            #---------------------------------------------------------------------------
            '''
            Put post ITERATION calculations HERE
            '''

            #Advance to the next iteration
            ITERATION += 1

            #RESET INDEX COUNTERS
            PSPC_INDX_DENS = 0
            PSPC_INDX_TEMP = 0
            ATOM_INDX_DENS = 0
            MOL_INDX_DENS = 0
            ION_INDX_DENS = 0
            PTA1DXR_INDX_TEMP = 0
            PTA1DYP_INDX_TEMP = 0
            PTA1DZT_INDX_TEMP = 0
            PDA1DXR_INDX_DENS = 0
            PDA1DYP_INDX_DENS = 0
            PDA1DZT_INDX_DENS = 0
            ADA1DXR_INDX_DENS = 0
            ADA1DYP_INDX_DENS = 0
            ADA1DZT_INDX_DENS = 0
            MDA1DXR_INDX_DENS = 0
            MDA1DYP_INDX_DENS = 0
            MDA1DZT_INDX_DENS = 0
            IDA1DXR_INDX_DENS = 0
            IDA1DYP_INDX_DENS = 0
            IDA1DZT_INDX_DENS = 0
            PT2YP_ZT_INDEX_TEMP = 0
            PT2XR_ZT_INDEX_TEMP = 0
            PT2XR_YP_INDEX_TEMP = 0
            PD2XR_YP_INDEX_DENS = 0
            PD2XR_ZT_INDEX_DENS = 0
            PD2YP_ZT_INDEX_DENS = 0
            AD2XR_YP_INDEX_DENS = 0
            AD2XR_ZT_INDEX_DENS = 0
            AD2YP_ZT_INDEX_DENS = 0
            MD2XR_YP_INDEX_DENS = 0
            MD2XR_ZT_INDEX_DENS = 0
            MD2YP_ZT_INDEX_DENS = 0
            ID2XR_YP_INDEX_DENS = 0
            ID2XR_ZT_INDEX_DENS = 0
            ID2YP_ZT_INDEX_DENS = 0
            PT3DXR_INDEX1_TEMP = 0
            PD3DXR_INDEX1_DENS = 0
            AD3DXR_INDEX1_DENS = 0
            MD3DXR_INDEX1_DENS = 0
            ID3DXR_INDEX1_DENS = 0

        #Advance the time step number
        if ('NEXT TIME CYCLE STARTS, SKIP READING' in FILE_OUT_LINES[i]):

            ITERATION = ITERATION - 1
            '''
            Put post TIME_STP Calculations Here
            '''
            #Advance to the next timestep
            TIME_STP += 1

            #RESET INDEX COUNTERS
            PSPC_INDX_DENS = 0
            PSPC_INDX_TEMP = 0
            ATOM_INDX_DENS = 0
            MOL_INDX_DENS = 0
            ION_INDX_DENS = 0
            PTA1DXR_INDX_TEMP = 0
            PTA1DYP_INDX_TEMP = 0
            PTA1DZT_INDX_TEMP = 0
            PDA1DXR_INDX_DENS = 0
            PDA1DYP_INDX_DENS = 0
            PDA1DZT_INDX_DENS = 0
            ADA1DXR_INDX_DENS = 0
            ADA1DYP_INDX_DENS = 0
            ADA1DZT_INDX_DENS = 0
            MDA1DXR_INDX_DENS = 0
            MDA1DYP_INDX_DENS = 0
            MDA1DZT_INDX_DENS = 0
            IDA1DXR_INDX_DENS = 0
            IDA1DYP_INDX_DENS = 0
            IDA1DZT_INDX_DENS = 0
            PT2YP_ZT_INDEX_TEMP = 0
            PT2XR_ZT_INDEX_TEMP = 0
            PT2XR_YP_INDEX_TEMP = 0
            PD2XR_YP_INDEX_DENS = 0
            PD2XR_ZT_INDEX_DENS = 0
            PD2YP_ZT_INDEX_DENS = 0
            AD2XR_YP_INDEX_DENS = 0
            AD2XR_ZT_INDEX_DENS = 0
            AD2YP_ZT_INDEX_DENS = 0
            MD2XR_YP_INDEX_DENS = 0
            MD2XR_ZT_INDEX_DENS = 0
            MD2YP_ZT_INDEX_DENS = 0
            ID2XR_YP_INDEX_DENS = 0
            ID2XR_ZT_INDEX_DENS = 0
            ID2YP_ZT_INDEX_DENS = 0
            PT3DXR_INDEX1_TEMP = 0
            PD3DXR_INDEX1_DENS = 0
            AD3DXR_INDEX1_DENS = 0
            MD3DXR_INDEX1_DENS = 0
            ID3DXR_INDEX1_DENS = 0
            ITERATION = 0

#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# End of output file reading

    #Plasma Temperature Data Array

    try:

        #0-D DA
        IC.build_DA_0D(VOL_AVG_DICT,VPTA,'PLS_SPECIES',TIME_STP_NUM,ITERATION_NUM,PLASMA_SPC_NAMES_TEMP,'Block Average Plasma Ion Temperature','eV','TEMP',DATASET_DICT,'PLS_BLA_TEMP',FILE_NAME)


        #1-D XR DA
        IC.build_DA_1D(VOL_AVG_DICT,PTA1DXR,'PLS_SPECIES',TIME_STP_NUM,ITERATION_NUM,PLASMA_SPC_NAMES_TEMP,'X or Radial Plasma Ion Temperature','eV','XRTEMP',DATASET_DICT,'PLS_XR_TEMP',FILE_NAME,'XR_POSITION',XR_NUM)

        #1-D YP DA
        IC.build_DA_1D(VOL_AVG_DICT,PTA1DYP,'PLS_SPECIES',TIME_STP_NUM,ITERATION_NUM,PLASMA_SPC_NAMES_TEMP,'Y or Poloidal Plasma Ion Temperature','eV','YPTEMP',DATASET_DICT,'PLS_YP_TEMP',FILE_NAME,'YP_POSITION',YP_NUM)

        #1-D ZT DA
        IC.build_DA_1D(VOL_AVG_DICT,PTA1DZT,'PLS_SPECIES',TIME_STP_NUM,ITERATION_NUM,PLASMA_SPC_NAMES_TEMP,'Z or Toroidal Plasma Ion Temperature','eV','ZTEMP',DATASET_DICT,'PLS_ZT_TEMP',FILE_NAME,'ZT_POSITION',ZT_NUM)


        #2-D YP across ZT data, avg XR
        IC.build_DA_2D(VOL_AVG_DICT,PT2YP_ZT,'PLS_SPECIES',TIME_STP_NUM,ITERATION_NUM,PLASMA_SPC_NAMES_TEMP,'2D Y or Poloidal Plasma Ion Temp Data, avg XR','eV','YP_ZT_TEMP',DATASET_DICT,'PLS_YP_ZT_TEMP_2D',FILE_NAME,'YP_POSITION','ZT_POSITION',YP_NUM,ZT_NUM)

        #2-D XR across YP data, avg ZT
        IC.build_DA_2D(VOL_AVG_DICT,PT2XR_YP,'PLS_SPECIES',TIME_STP_NUM,ITERATION_NUM,PLASMA_SPC_NAMES_TEMP,' 2D X or Radial Plasma Ion Temperature, avg ZT','eV','XR_YP_TEMP',DATASET_DICT,'PLS_XR_YP_TEMP_2D',FILE_NAME,'XR_POSITION','YP_POSITION',XR_NUM,YP_NUM)

        #2-D XR across ZT data, avg YP
        IC.build_DA_2D(VOL_AVG_DICT,PT2XR_ZT,'PLS_SPECIES',TIME_STP_NUM,ITERATION_NUM,PLASMA_SPC_NAMES_TEMP,' 2D X or Radial Plasma Ion Temperature, avg YP','eV','XR_ZT_TEMP',DATASET_DICT,'PLS_XR_ZT_TEMP_2D',FILE_NAME,'XR_POSITION','ZT_POSITION',XR_NUM,ZT_NUM)

        #3-D XR across YP and ZT data, avg YP
        IC.build_DA_3D(VOL_AVG_DICT,PT3DXR,'PLS_SPECIES',TIME_STP_NUM,ITERATION_NUM,PLASMA_SPC_NAMES_TEMP,' 3D X or Radial Plasma Ion Temperature','eV','XR_3D_TEMP',DATASET_DICT,'PLS_XR_TEMP_3D',FILE_NAME,'XR_POSITION','YP_POSITION','ZT_POSITION',XR_NUM,YP_NUM,ZT_NUM)



        #Plasma Density Data Array

        #0-D DA
        IC.build_DA_0D(VOL_AVG_DICT,VPDA,'PLS_SPECIES',TIME_STP_NUM,ITERATION_NUM,PLASMA_SPC_NAMES_DENS,'Block Average Plasma Ion Density','cm-3','DENS',DATASET_DICT,'PLS_BLA_DENS',FILE_NAME)

        #1-D XR DA
        IC.build_DA_1D(VOL_AVG_DICT,PDA1DXR,'PLS_SPECIES',TIME_STP_NUM,ITERATION_NUM,PLASMA_SPC_NAMES_DENS,'X or Radial Plasma Ion Density','cm-3','XRDENS',DATASET_DICT,'PLS_XR_DENS',FILE_NAME,'XR_POSITION',XR_NUM)

        #1-D YP DA
        IC.build_DA_1D(VOL_AVG_DICT,PDA1DYP,'PLS_SPECIES',TIME_STP_NUM,ITERATION_NUM,PLASMA_SPC_NAMES_DENS,'Y or Poloidal Plasma Ion Density','cm-3','YPDENS',DATASET_DICT,'PLS_YP_DENS',FILE_NAME,'YP_POSITION',YP_NUM)

        #1-D ZT DA
        IC.build_DA_1D(VOL_AVG_DICT,PDA1DZT,'PLS_SPECIES',TIME_STP_NUM,ITERATION_NUM,PLASMA_SPC_NAMES_DENS,'Z or Toroidal Plasma Ion Density','cm-3','ZTDENS',DATASET_DICT,'PLS_ZT_DENS',FILE_NAME,'ZT_POSITION',ZT_NUM)


        #2-D YP across ZT data, avg XR
        IC.build_DA_2D(VOL_AVG_DICT,PD2YP_ZT,'PLS_SPECIES',TIME_STP_NUM,ITERATION_NUM,PLASMA_SPC_NAMES_DENS,'2D Y or Poloidal Plasma Ion Density, avg XR','cm-3','YP_ZT_DENS',DATASET_DICT,'PLS_YP_ZT_DENS_2D',FILE_NAME,'YP_POSITION','ZT_POSITION',YP_NUM,ZT_NUM)

        #2-D XR across YP data, avg ZT
        IC.build_DA_2D(VOL_AVG_DICT,PD2XR_YP,'PLS_SPECIES',TIME_STP_NUM,ITERATION_NUM,PLASMA_SPC_NAMES_DENS,' 2D X or Radial Plasma Ion Density, avg ZT','cm-3','XR_YP_DENS',DATASET_DICT,'PLS_XR_YP_DENS_2D',FILE_NAME,'XR_POSITION','YP_POSITION',XR_NUM,YP_NUM)

        #2-D XR across ZT data, avg YP
        IC.build_DA_2D(VOL_AVG_DICT,PD2XR_ZT,'PLS_SPECIES',TIME_STP_NUM,ITERATION_NUM,PLASMA_SPC_NAMES_DENS,' 2D X or Radial Plasma Ion Density, avg YP','cm-3','XR_ZT_DENS',DATASET_DICT,'PLS_XR_ZT_DENS_2D',FILE_NAME,'XR_POSITION','ZT_POSITION',XR_NUM,ZT_NUM)

        #3-D XR across YP and ZT data, AVG
        IC.build_DA_3D(VOL_AVG_DICT,PD3DXR,'PLS_SPECIES',TIME_STP_NUM,ITERATION_NUM,PLASMA_SPC_NAMES_DENS,' 3D X or Radial Plasma Ion Temperature','cm-3','XR_3D_DENS',DATASET_DICT,'PLS_XR_DENS_3D',FILE_NAME,'XR_POSITION','YP_POSITION','ZT_POSITION',XR_NUM,YP_NUM,ZT_NUM)


        #Atom Density Data Array

        #0-D DA
        IC.build_DA_0D(VOL_AVG_DICT,VADA,'ATM_SPECIES',TIME_STP_NUM,ITERATION_NUM,ATOM_SPC_NAMES_DENS,'Block Average Atom Denisty','cm-3','DENS',DATASET_DICT,'ATOM_BLA_DENS',FILE_NAME)

        #1-D XR DA
        IC.build_DA_1D(VOL_AVG_DICT,ADA1DXR,'ATM_SPECIES',TIME_STP_NUM,ITERATION_NUM,ATOM_SPC_NAMES_DENS,'X or Radial Atom Density','cm-3','XRDENS',DATASET_DICT,'ATM_XR_DENS',FILE_NAME,'XR_POSITION',XR_NUM)

        #1-D YP DA
        IC.build_DA_1D(VOL_AVG_DICT,ADA1DYP,'ATM_SPECIES',TIME_STP_NUM,ITERATION_NUM,ATOM_SPC_NAMES_DENS,'Y or Poloidal Atom Density','cm-3','YPDENS',DATASET_DICT,'ATM_YP_DENS',FILE_NAME,'YP_POSITION',YP_NUM)

        #1-D ZT DA
        IC.build_DA_1D(VOL_AVG_DICT,ADA1DZT,'ATM_SPECIES',TIME_STP_NUM,ITERATION_NUM,ATOM_SPC_NAMES_DENS,'Z or Toroidal Atom Density','cm-3','ZTDENS',DATASET_DICT,'ATM_ZT_DENS',FILE_NAME,'ZT_POSITION',ZT_NUM)

        #2-D YP across ZT data, avg XR
        IC.build_DA_2D(VOL_AVG_DICT,AD2YP_ZT,'ATM_SPECIES',TIME_STP_NUM,ITERATION_NUM,ATOM_SPC_NAMES_DENS,'2D Y or Poloidal Atom Density, avg XR','cm-3','YP_ZT_DENS',DATASET_DICT,'ATM_YP_ZT_DENS_2D',FILE_NAME,'YP_POSITION','ZT_POSITION',YP_NUM,ZT_NUM)

        #2-D XR across YP data, avg ZT
        IC.build_DA_2D(VOL_AVG_DICT,AD2XR_YP,'ATM_SPECIES',TIME_STP_NUM,ITERATION_NUM,ATOM_SPC_NAMES_DENS,' 2D X or Radial Atom Density, avg ZT','cm-3','XR_YP_DENS',DATASET_DICT,'ATM_XR_YP_DENS_2D',FILE_NAME,'XR_POSITION','YP_POSITION',XR_NUM,YP_NUM)

        #2-D XR across ZT data, avg YP
        IC.build_DA_2D(VOL_AVG_DICT,AD2XR_ZT,'ATM_SPECIES',TIME_STP_NUM,ITERATION_NUM,ATOM_SPC_NAMES_DENS,' 2D X or Radial Atom Density, avg YP','cm-3','XR_ZT_DENS',DATASET_DICT,'ATM_XR_ZT_DENS_2D',FILE_NAME,'XR_POSITION','ZT_POSITION',XR_NUM,ZT_NUM)

        #3-D XR across YP and ZT data, AVG
        IC.build_DA_3D(VOL_AVG_DICT,AD3DXR,'ATM_SPECIES',TIME_STP_NUM,ITERATION_NUM,ATOM_SPC_NAMES_DENS,' 3D X or Radial Atom Density','cm-3','XR_3D_DENS',DATASET_DICT,'ATM_XR_DENS_3D',FILE_NAME,'XR_POSITION','YP_POSITION','ZT_POSITION',XR_NUM,YP_NUM,ZT_NUM)


        #Molecule Density Data Array

        #0-D DA
        IC.build_DA_0D(VOL_AVG_DICT,VMDA,'MOL_SPECIES',TIME_STP_NUM,ITERATION_NUM,MOL_SPC_NAMES_DENS,'Block Avergae Molecule Density','cm-3','DENS',DATASET_DICT,'MOL_BLA_DENS',FILE_NAME)

        #1-D XR DA
        IC.build_DA_1D(VOL_AVG_DICT,MDA1DXR,'MOL_SPECIES',TIME_STP_NUM,ITERATION_NUM,MOL_SPC_NAMES_DENS,'X or Radial Molecule Density','cm-3','XRDENS',DATASET_DICT,'MOL_XR_DENS',FILE_NAME,'XR_POSITION',XR_NUM)

        #1-D YP DA
        IC.build_DA_1D(VOL_AVG_DICT,MDA1DYP,'MOL_SPECIES',TIME_STP_NUM,ITERATION_NUM,MOL_SPC_NAMES_DENS,'Y or Poloidal Molecule Density','cm-3','YPDENS',DATASET_DICT,'MOL_YP_DENS',FILE_NAME,'YP_POSITION',YP_NUM)

        #1-D ZT DA
        IC.build_DA_1D(VOL_AVG_DICT,MDA1DZT,'MOL_SPECIES',TIME_STP_NUM,ITERATION_NUM,MOL_SPC_NAMES_DENS,'Z or Toroidal Molecule Denisty','cm-3','ZTDENS',DATASET_DICT,'MOL_ZT_DENS',FILE_NAME,'ZT_POSITION',ZT_NUM)

        #2-D YP across ZT data, avg XR
        IC.build_DA_2D(VOL_AVG_DICT,MD2YP_ZT,'MOL_SPECIES',TIME_STP_NUM,ITERATION_NUM,MOL_SPC_NAMES_DENS,'2D Y or Poloidal Molecule Density, avg XR','cm-3','YP_ZT_DENS',DATASET_DICT,'MOL_YP_ZT_DENS_2D',FILE_NAME,'YP_POSITION','ZT_POSITION',YP_NUM,ZT_NUM)

        #2-D XR across YP data, avg ZT
        IC.build_DA_2D(VOL_AVG_DICT,MD2XR_YP,'MOL_SPECIES',TIME_STP_NUM,ITERATION_NUM,MOL_SPC_NAMES_DENS,' 2D X or Radial Molecule Density, avg ZT','cm-3','XR_YP_DENS',DATASET_DICT,'MOL_XR_YP_DENS_2D',FILE_NAME,'XR_POSITION','YP_POSITION',XR_NUM,YP_NUM)

        #2-D XR across ZT data, avg YP
        IC.build_DA_2D(VOL_AVG_DICT,MD2XR_ZT,'MOL_SPECIES',TIME_STP_NUM,ITERATION_NUM,MOL_SPC_NAMES_DENS,' 2D X or Radial Molecule Density, avg YP','cm-3','XR_ZT_DENS',DATASET_DICT,'MOL_XR_ZT_DENS_2D',FILE_NAME,'XR_POSITION','ZT_POSITION',XR_NUM,ZT_NUM)

        #3-D XR across YP and ZT data, AVG
        IC.build_DA_3D(VOL_AVG_DICT,MD3DXR,'MOL_SPECIES',TIME_STP_NUM,ITERATION_NUM,MOL_SPC_NAMES_DENS,' 3D X or Radial Molecule Density','cm-3','XR_3D_DENS',DATASET_DICT,'MOL_XR_DENS_3D',FILE_NAME,'XR_POSITION','YP_POSITION','ZT_POSITION',XR_NUM,YP_NUM,ZT_NUM)


        #Test Ion Density Data Array

        #0-D DA
        IC.build_DA_0D(VOL_AVG_DICT,VIDA,'ION_SPECIES',TIME_STP_NUM,ITERATION_NUM,ION_SPC_NAMES_DENS,'Block Average Test Ion Density','cm-3','DENS',DATASET_DICT,'ION_BLA_DENS',FILE_NAME)

        #1-D XR DA
        IC.build_DA_1D(VOL_AVG_DICT,IDA1DXR,'ION_SPECIES',TIME_STP_NUM,ITERATION_NUM,ION_SPC_NAMES_DENS,'X or Radial Test Ion Density','cm-3','XRDENS',DATASET_DICT,'ION_XR_DENS',FILE_NAME,'XR_POSITION',XR_NUM)

        #1-D YP DA
        IC.build_DA_1D(VOL_AVG_DICT,IDA1DYP,'ION_SPECIES',TIME_STP_NUM,ITERATION_NUM,ION_SPC_NAMES_DENS,'Y or Poloidal Test Ion Density','cm-3','YPDENS',DATASET_DICT,'ION_YP_DENS',FILE_NAME,'YP_POSITION',YP_NUM)

        #1-D ZT DA
        IC.build_DA_1D(VOL_AVG_DICT,IDA1DZT,'ION_SPECIES',TIME_STP_NUM,ITERATION_NUM,ION_SPC_NAMES_DENS,'Z or Toroidal Test Ion Denisty','cm-3','ZTDENS',DATASET_DICT,'ION_ZT_DENS',FILE_NAME,'ZT_POSITION',ZT_NUM)

        #2-D YP across ZT data, avg XR
        IC.build_DA_2D(VOL_AVG_DICT,ID2YP_ZT,'ION_SPECIES',TIME_STP_NUM,ITERATION_NUM,ION_SPC_NAMES_DENS,'2D Y or Poloidal Test Ion Density, avg XR','cm-3','YP_ZT_DENS',DATASET_DICT,'ION_YP_ZT_DENS_2D',FILE_NAME,'YP_POSITION','ZT_POSITION',YP_NUM,ZT_NUM)

        #2-D XR across YP data, AVG ZT
        IC.build_DA_2D(VOL_AVG_DICT,ID2XR_YP,'ION_SPECIES',TIME_STP_NUM,ITERATION_NUM,ION_SPC_NAMES_DENS,' 2D X or Radial Test Ion Density, avg ZT','cm-3','XR_YP_DENS',DATASET_DICT,'ION_XR_YP_DENS_2D',FILE_NAME,'XR_POSITION','YP_POSITION',XR_NUM,YP_NUM)

        #2-D XR across ZT data, AVG YP
        IC.build_DA_2D(VOL_AVG_DICT,ID2XR_ZT,'ION_SPECIES',TIME_STP_NUM,ITERATION_NUM,ION_SPC_NAMES_DENS,' 2D X or Radial Test Ion Density, avg YP','cm-3','XR_ZT_DENS',DATASET_DICT,'ION_XR_ZT_DENS_2D',FILE_NAME,'XR_POSITION','ZT_POSITION',XR_NUM,ZT_NUM)

        #3-D XR across YP and ZT data, AVG
        IC.build_DA_3D(VOL_AVG_DICT,ID3DXR,'ION_SPECIES',TIME_STP_NUM,ITERATION_NUM,ION_SPC_NAMES_DENS,' 3D X or Radial Test Ion Density','cm-3','XR_3D_DENS',DATASET_DICT,'ION_XR_DENS_3D',FILE_NAME,'XR_POSITION','YP_POSITION','ZT_POSITION',XR_NUM,YP_NUM,ZT_NUM)

    except:

        print('No supported Output Data Types')
# End of building DataArrays




    #Reading and building data from fort files if present


    '''
    '''
       #Read Data from atom density fort file
    if PLS_TEMP_DATA_FILE != 'NONE':
        #Build array from fort 90 files
        FT_PLS_SPECIES = []
        #Sweep for atoms in the list
        FT_PLS_SPECIES = IC.FT_get_species(PLS_TEMP_FT_DATA_LINES,FT_PLS_SPECIES)
        #Build array to be filled
        FT_PLS_TEMP_ARRAY = IC.FT_build_array(PLS_NUM,ZT_NUM,YP_NUM,XR_NUM,ITERATION_NUM,TIME_STP_NUM)
        #Read fort file and fill data array
        FT_PLS_TEMP_ARRAY = IC.FT_get_data(PLS_TEMP_FT_DATA_LINES,FT_PLS_TEMP_ARRAY,'PLASMA TEMPERATURE',ITERATION_NUM,ZT_NUM,YP_NUM,XR_NUM,PLASMA_SPC_NAMES_TEMP,TIME_STP_NUM)
        #Build DataArray
        FT_PLS_TEMP_DA,DATASET_DICT = IC.FT_build_DA(FT_PLS_TEMP_ARRAY,'PLS_SPECIES','FT_PLS_TEMP','eV','Eirene plasma temperature data from fort files',PLASMA_SPC_NAMES_TEMP,ZT_NUM,YP_NUM,XR_NUM,ITERATION_NUM,TIME_STP_NUM,DATASET_DICT)

     #Read Data from plasma density fort file
    if PLS_DENS_DATA_FILE != 'NONE':
        #Build array from fort 90 files
        FT_PLS_SPECIES = []
        #Sweep for atoms in the list
        FT_PLS_SPECIES = IC.FT_get_species(PLS_DENS_FT_DATA_LINES,FT_PLS_SPECIES)
        #Build array to be filled
        FT_PLS_DENS_ARRAY = IC.FT_build_array(PLS_NUM,ZT_NUM,YP_NUM,XR_NUM,ITERATION_NUM,TIME_STP_NUM)
        #Read fort file and fill data array
        FT_PLS_DENS_ARRAY = IC.FT_get_data(PLS_DENS_FT_DATA_LINES,FT_PLS_DENS_ARRAY,'PLASMA DENSITY (BULK PARTICLES)',ITERATION_NUM,ZT_NUM,YP_NUM,XR_NUM,PLASMA_SPC_NAMES_DENS,TIME_STP_NUM)
        #Build DataArray
        FT_PLS_DENS_DA,DATASET_DICT = IC.FT_build_DA(FT_PLS_DENS_ARRAY,'PLS_SPECIES','FT_PLS_DENS','cm-3','Eirene plasma density data from fort files',PLASMA_SPC_NAMES_DENS,ZT_NUM,YP_NUM,XR_NUM,ITERATION_NUM,TIME_STP_NUM,DATASET_DICT)

    #Read Data from atom density fort file
    if ATM_DENS_DATA_FILE != 'NONE':


        #Build array from fort 90 files
        FT_ATM_SPECIES = []
        #Sweep for atoms in the list
        FT_ATM_SPECIES = IC.FT_get_species(ATM_DENS_FT_DATA_LINES,FT_ATM_SPECIES)
        #Build array to be filled
        FT_ATM_DENS_ARRAY = IC.FT_build_array(ATM_NUM,ZT_NUM,YP_NUM,XR_NUM,ITERATION_NUM,TIME_STP_NUM)
        #Read fort file and fill data array
        FT_ATM_DENS_ARRAY = IC.FT_get_data(ATM_DENS_FT_DATA_LINES,FT_ATM_DENS_ARRAY,'PARTICLE DENSITY (ATOMS)',ITERATION_NUM,ZT_NUM,YP_NUM,XR_NUM,ATOM_SPC_NAMES_DENS,TIME_STP_NUM)
        #Build DataArray
        FT_ATM_DENS_DA,DATASET_DICT = IC.FT_build_DA(FT_ATM_DENS_ARRAY,'ATM_SPECIES','FT_ATM_DENS','cm-3','Eirene atom density data from fort files',ATOM_SPC_NAMES_DENS,ZT_NUM,YP_NUM,XR_NUM,ITERATION_NUM,TIME_STP_NUM,DATASET_DICT)

    #Read Data from molecule density fort file
    if MOL_DENS_DATA_FILE != 'NONE':
        #Build array from fort 90 files
        FT_MOL_SPECIES = []
        #Sweep for atoms in the list
        FT_MOL_SPECIES = IC.FT_get_species(MOL_DENS_FT_DATA_LINES,FT_MOL_SPECIES)
        #Build array to be filled
        FT_MOL_DENS_ARRAY = IC.FT_build_array(MOL_NUM,ZT_NUM,YP_NUM,XR_NUM,ITERATION_NUM,TIME_STP_NUM)
        #Read fort file and fill data array
        FT_MOL_DENS_ARRAY = IC.FT_get_data(MOL_DENS_FT_DATA_LINES,FT_MOL_DENS_ARRAY,'PARTICLE DENSITY (MOLECULES)',ITERATION_NUM,ZT_NUM,YP_NUM,XR_NUM,MOL_SPC_NAMES_DENS,TIME_STP_NUM)
        #Build DataArray
        FT_MOL_DENS_DA,DATASET_DICT = IC.FT_build_DA(FT_MOL_DENS_ARRAY,'MOL_SPECIES','FT_MOL_DENS','cm-3','Eirene molecule density data from fort files',MOL_SPC_NAMES_DENS,ZT_NUM,YP_NUM,XR_NUM,ITERATION_NUM,TIME_STP_NUM,DATASET_DICT)

    #Read Data from atom density fort file
    if ION_DENS_DATA_FILE != 'NONE':
        #Build array from fort 90 files
        FT_ION_SPECIES = []
        #Sweep for atoms in the list
        FT_ION_SPECIES = IC.FT_get_species(ION_DENS_FT_DATA_LINES,FT_ION_SPECIES)
        #Build array to be filled
        FT_ION_DENS_ARRAY = IC.FT_build_array(ION_NUM,ZT_NUM,YP_NUM,XR_NUM,ITERATION_NUM,TIME_STP_NUM)
        #Read fort file and fill data array
        FT_ION_DENS_ARRAY = IC.FT_get_data(ION_DENS_FT_DATA_LINES,FT_ION_DENS_ARRAY,'PARTICLE DENSITY (TEST IONS)',ITERATION_NUM,ZT_NUM,YP_NUM,XR_NUM,ION_SPC_NAMES_DENS,TIME_STP_NUM)
        #Build DataArray
        FT_ION_DENS_DA,DATASET_DICT = IC.FT_build_DA(FT_ION_DENS_ARRAY,'ION_SPECIES','FT_ION_DENS','cm-3','Eirene test ion density data from fort files',ION_SPC_NAMES_DENS,ZT_NUM,YP_NUM,XR_NUM,ITERATION_NUM,TIME_STP_NUM,DATASET_DICT)

# Build DataSet from Data Arrays


    try:

        EIR_DS_OUT = xr.Dataset(DATASET_DICT)
        EIR_DS_OUT.attrs['BLOCK_11_CL'] = NUM_PRINTOUT_CONDITIONAL_LIST
        EIR_DS_OUT.attrs['VOL_AVG_FLAGS'] = list(VOL_AVG_DICT)

    except:

        print('Could not read block 11 correctly')
    try:

        EIR_DS_OUT.attrs['INFO'] = META_DESCRIPTION_LINE

    except:

        print('Could not find a description of the file to save')

    try:
        EIR_DS_OUT.attrs['DATE'] = DATE
        EIR_DS_OUT.attrs['TIME'] = TIME
    except:
        print('Could not get Date and Time')



    EIR_DS_OUT.to_netcdf(DIRECTORY + FILE_NAME + '.nc')

#return final DataSet


    return EIR_DS_OUT


















def batch(DS_LIST,BATCH_NAME = 'BATCH_NAME_LEFT_EMPTY',DIRECTORY = ''):
    '''
    This function takes a list of the '.nc' file names that the user wishes to concatenate into a single Dataset
    '''
    #----------------------------------
    import pandas as pd
    import xarray as xr
    #----------------------------------

    NC_LIST = []
    for i in DS_LIST:
        NC_LIST.append(xr.open_dataset(i))
    NC_LIST.reverse()
    EIR_XBATCH_OUT = xr.concat(NC_LIST, pd.Index( list(range(len(DS_LIST))), name = 'BATCHID'))
    EIR_XBATCH_OUT.attrs['INFO'] = BATCH_NAME
    for i in range(len(NC_LIST)):

        EIR_XBATCH_OUT.attrs['BATCH%i' % i] = NC_LIST[i].INFO

    EIR_XBATCH_OUT.to_netcdf(DIRECTORY + BATCH_NAME + 'EIR_XBATCH_OUT.nc')

    return EIR_XBATCH_OUT

def auto(DIRECTORY = './',BATCH_NAME = 'BATCH_NAME_LEFT_EMPTY'):
    '''
    This function takes a directory which contains a set of EIRENE input and output files. It creates
    a dataset for each run in the directory, and then it creates a dataset which is a concatenation of
    all of the datasets in that directory.
    '''
    #----------------------------------
    import os
    #----------------------------------

    FILES = os.listdir(DIRECTORY)
    FILES.sort()


    CLEAN_FILE_LIST = []
    NC_LIST = []
    for i in FILES:

        if 'run' in i:
            CLEAN_FILE_LIST.append(i)

    for i in CLEAN_FILE_LIST:

        run(DIRECTORY + '%s/input.dat' % i,DIRECTORY+'%s/run.log' % i,DIRECTORY + '%s/fort.90' % i,DIRECTORY + '%s/fort.91' % i,DIRECTORY + '%s/fort.92' % i,DIRECTORY + '%s/fort.93' % i,DIRECTORY + '%s/fort.94' % i,DIRECTORY + '%s/' %i)
        NC_LIST.append(DIRECTORY + '%s/input.nc' %i)

    batch(NC_LIST,BATCH_NAME,DIRECTORY)








    '''
    FILES_CLEAN_LIST = []
    for i in FILES:
        if '.in' in i or '.out' in i :
            FILES_CLEAN_LIST.append(DIRECTORY + i)


    NC_LIST = []
    INXSTOP = 0
    while (INXSTOP < (len(FILES_CLEAN_LIST)-1)):
        print('-------------------------')
        print(FILES_CLEAN_LIST[INXSTOP])
        print(FILES_CLEAN_LIST[INXSTOP+1])
        print('-------------------------')
        run(FILES_CLEAN_LIST[INXSTOP],FILES_CLEAN_LIST[INXSTOP + 1],DIRECTORY)
        INXSTOP +=2

    FILES = os.listdir(DIRECTORY)
    for i in FILES:
        if '.nc' in i:
            NC_LIST.append(DIRECTORY + i)
    batch(NC_LIST,BATCH_NAME,DIRECTORY)
    '''
    return

#---------------------------------------------------------------------------------------------------------------------------------------------
##############################################################################################################################################
##############################################################################################################################################
##############################################################################################################################################
##############################################################################################################################################
##############################################################################################################################################
#---------------------------------------------------------------------------------------------------------------------------------------------
#
#
